/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sjune' at '2/27/15 1:05 AM' with Gradle 1.11
 *
 * @author sjune, @date 2/27/15 1:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
